/* WGS84 geometry and conservative research-coverage planning. No network dependencies. */
(function(root){
'use strict';
const R=6371008.8,rad=Math.PI/180;
function coordinate(c){return Array.isArray(c)&&c.length>=2&&c.slice(0,2).every(v=>typeof v==='number'&&Number.isFinite(v))&&Math.abs(c[0])<=180&&Math.abs(c[1])<=90;}
function point(p){const raw=[p.longitude_wgs84,p.latitude_wgs84];if(raw.some(v=>v===null||v===undefined||String(v).trim()===''))return null;const c=raw.map(Number);return coordinate(c)?c:null;}
function distance(a,b){const x=(b[1]-a[1])*rad,y=(b[0]-a[0])*rad;const h=Math.sin(x/2)**2+Math.cos(a[1]*rad)*Math.cos(b[1]*rad)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(Math.min(1,h)));}
function index(coords){if(!Array.isArray(coords)||coords.length<2||!coords.every(coordinate))throw Error('Route must be a WGS84 LineString with at least two valid points.');const cumulative=[0];for(let i=1;i<coords.length;i++)cumulative.push(cumulative[i-1]+distance(coords[i-1],coords[i]));if(cumulative.at(-1)<1)throw Error('Route has no measurable length.');return {coords,cumulative,length:cumulative.at(-1)};}
function candidates(route,p){const cos=Math.cos(p[1]*rad),out=[];for(let i=0;i<route.coords.length-1;i++){const a=route.coords[i],b=route.coords[i+1];const ax=(a[0]-p[0])*rad*R*cos,ay=(a[1]-p[1])*rad*R,bx=(b[0]-p[0])*rad*R*cos,by=(b[1]-p[1])*rad*R,dx=bx-ax,dy=by-ay;const t=Math.max(0,Math.min(1,-(ax*dx+ay*dy)/(dx*dx+dy*dy||1)));const coord=[a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])];out.push({along:route.cumulative[i]+t*(route.cumulative[i+1]-route.cumulative[i]),offset:distance(p,coord),coord,segment:i});}return out;}
function project(route,p,previous=null,maxTravel=Infinity){const all=candidates(route,p);let best=all.reduce((a,b)=>a.offset<=b.offset?a:b);const near=all.filter(x=>x.offset<=best.offset+25);if(previous!==null){const plausible=near.filter(x=>Math.abs(x.along-previous)<=maxTravel);if(plausible.length)best=plausible.reduce((a,b)=>Math.abs(a.along-previous)<Math.abs(b.along-previous)?a:b);else return {...best,ambiguous:true};}const ambiguous=near.some(x=>Math.abs(x.along-best.along)>1000&&(previous===null||Math.abs(x.along-previous)<=maxTravel));return {...best,ambiguous};}
function at(route,meters){const m=Math.max(0,Math.min(route.length,meters));let i=route.cumulative.findIndex(x=>x>=m);if(i<=0)return route.coords[0];const a=route.coords[i-1],b=route.coords[i],t=(m-route.cumulative[i-1])/(route.cumulative[i]-route.cumulative[i-1]||1);return [a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])];}
function slice(route,start,end){return [at(route,start),...route.coords.filter((_,i)=>route.cumulative[i]>start&&route.cumulative[i]<end),at(route,end)];}
function associate(route,chargers,{corridor=2000,excludeTesla=true}={}){return chargers.map(p=>{const coord=point(p);const snap=coord?project(route,coord):null;let reason='';if(!snap)reason='No coordinate';else if(!['A','B'].includes(p.verification_tier))reason='Area estimate only';else if(snap.ambiguous)reason='Repeated route section';else if(snap.offset>corridor)reason='Outside corridor';else if(excludeTesla&&/tesla|特斯拉/i.test(p.name+' '+p.operator))reason='Vehicle access unconfirmed';return {p,coord,snap,eligible:!reason,reason};}).sort((a,b)=>(a.snap?.along??Infinity)-(b.snap?.along??Infinity));}
function next(rows,progress){const ahead=rows.filter(r=>r.eligible&&r.snap.along>=progress-50);const first=ahead[0]||null;const backup=first?ahead.find(r=>r.p.id!==first.p.id&&r.snap.along-first.snap.along>500&&distance(r.coord,first.coord)>300)||null:null;return {first,backup};}
function gaps(route,rows){const sorted=rows.filter(r=>r.eligible).sort((a,b)=>a.snap.along-b.snap.along);const sites=[];for(const row of sorted){if(!sites.length||row.snap.along-sites.at(-1).at>500)sites.push({at:row.snap.along,name:row.p.name,kind:'charger'});}const nodes=[{at:0,name:'Route start',kind:'boundary'},...sites,{at:route.length,name:'Route end',kind:'boundary'}];const spans=nodes.slice(1).map((to,i)=>({from:nodes[i],to,meters:to.at-nodes[i].at}));return {sites,spans,longest:spans.reduce((a,b)=>a.meters>=b.meters?a:b)};}
const api={coordinate,point,distance,index,project,at,slice,associate,next,gaps};if(typeof module!=='undefined')module.exports=api;root.RouteEngine=api;
})(typeof window==='undefined'?globalThis:window);
